version: 2.1
orbs:
  nix: eld/nix@1.0.0

executors:
  linux-machine:
    machine:
      image: ubuntu-2004:202111-02
  macos:
    macos:
      xcode: 13.3.0

workflows:
  build-flake:
    jobs:
      - check-flake:
          matrix:
            parameters:
              os: [linux-machine, macos]

jobs:
  check-flake:
    parameters:
      os:
        type: executor
        default: macos
        description: "Which system to run the flake check against"
    executor: << parameters.os >>
    steps:
      - checkout
      - nix/install
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Cachix Use
          command: |
            cachix use eld
      - run:
          name: Flake check
          command: nix flake check -v --show-trace
