version: 2.1
orbs:
  nix: eld/nix@1.1.1

executors:
  x86_64-linux:
    resource_class: large
    machine:
      image: ubuntu-2204:current
  # aarch64-linux:
  #   resource_class: arm.large
  #   machine:
  #     image: ubuntu-2204:current
  # x86_64-darwin:
  #   resource_class: macos.x86.medium.gen2
  #   macos:
  #     xcode: 14.2.0
  aarch64-darwin:
    resource_class: macos.m1.large.gen1
    macos:
      xcode: 14.3.1

workflows:
  build-flake:
    jobs:
      - check-flake:
          context:
            - nix
          matrix:
            parameters:
              os: [aarch64-darwin
                  , x86_64-linux
                  # I'm not running any active x86_64-darwin machines anymore, so no need to CI test this
                  # , x86_64-darwin
                  # I don't use aarch64-linux right now, so no use turning this on, for now
                  # , aarch64-linux
                  ]

jobs:
  check-flake:
    parameters:
      os:
        type: executor
        default: aarch64-darwin
        description: "Which system to run the flake check against"
    executor: << parameters.os >>
    environment:
      CACHIX_USER: eld
    steps:
      - checkout
      - nix/install:
          extra-conf: |
            auto-optimise-store = false
            sandbox = false
            sandbox-fallback = false
            keep-outputs = true
            keep-derivations = true
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eld.cachix.org-1:ddhUxMCAKZVJOVPUcGGWwB5UZfhlhG12rN4GRz8D7sk=
            trusted-substituters = https://cache.nixos.org https://eld.cachix.org
      - nix/install-cachix
      - nix/with-cachix:
          cachix-user: eld
          nix-command: nix flake check -j auto -v --show-trace --accept-flake-config --fallback --allow-import-from-derivation

