version: 2.1
orbs:
  nix: eld/nix@1.0.0

executors:
  x86_64-linux:
    resource_class: large
    machine:
      image: ubuntu-2204:current
  aarch64-linux:
    resource_class: arm.large
    machine:
      image: ubuntu-2204:current
  x86_64-darwin:
    resource_class: macos.x86.medium.gen2
    macos:
      xcode: 14.1.0
  aarch64-darwin:
    resource_class: macos.m1.large.gen1
    macos:
      xcode: 14.0.1

workflows:
  build-flake:
    jobs:
      - check-flake:
          context:
            - nix
          matrix:
            parameters:
              os: [x86_64-darwin
                  # , aarch64-darwin
                  , x86_64-linux
                  # , aarch64-linux
                  ]

jobs:
  check-flake:
    parameters:
      os:
        type: executor
        default: macos
        description: "Which system to run the flake check against"
    executor: << parameters.os >>
    environment:
      CACHIX_USER: eld
    steps:
      - checkout
      - nix/install
      - run:
          name: Install Cachix and Use Binary Cache
          command: |
            nix profile install github:nixos/nixpkgs/nixos-22.11#cachix && cachix use $CACHIX_USER
      - run:
          name: Flake check
          command: cachix watch-exec $CACHIX_USER -- nix flake check -j auto -v --show-trace --accept-flake-config
