name: "system build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v14.1
        env:
          NIX_VERSION: nix-2.5pre20211026_5667822
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: eld
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullName: kclejeune
      - name: Run Flake Checks
        run: |
          nix flake check -v --show-trace
        timeout-minutes: 240
