name: Check Nix Flake
on: [push, pull_request]
jobs:
    check:
      permissions:
        contents: read
        id-token: write
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - name: Check Nix flake inputs
          uses: DeterminateSystems/flake-checker-action@v5
        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@v4
        - name: Run the Magic Nix Cache
          uses: DeterminateSystems/magic-nix-cache-action@v2
        - name: Check Nix Flake
          run: nix flake check -j auto -v --show-trace --accept-flake-config --fallback --allow-import-from-derivation
